import type { Metadata } from "next";
import "./globals.css";
import { cookies } from "next/headers";
import Header from "./components/Header";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = cookies().get("theme")?.value;

  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={theme === "dark" ? "dark" : ""}
    >
      <body className="min-h-screen flex flex-col bg-secondary dark:bg-secondary-d dark:text-primary-d transition-colors duration-500">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
